import { StudioTemplate } from '../types/studio';

export const ASPECT_RATIO_PRESETS: {
  id: string;
  name: string;
  ratio: StudioTemplate['aspectRatio'];
  width: number;
  height: number;
  iconLabel: string;
  description: string;
}[] = [
  { id: '1:1', name: 'Square (1:1)', ratio: '1:1', width: 1080, height: 1080, iconLabel: '1:1', description: 'Instagram Post / Profile' },
  { id: '4:5', name: 'Portrait (4:5)', ratio: '4:5', width: 1080, height: 1350, iconLabel: '4:5', description: 'Instagram Feed Portrait' },
  { id: '9:16', name: 'Story / Shorts (9:16)', ratio: '9:16', width: 1080, height: 1920, iconLabel: '9:16', description: 'Reels / TikTok / Story' },
  { id: '16:9', name: 'Landscape (16:9)', ratio: '16:9', width: 1920, height: 1080, iconLabel: '16:9', description: 'YouTube Thumbnail / Banner' },
  { id: '4:3', name: 'Standard (4:3)', ratio: '4:3', width: 1440, height: 1080, iconLabel: '4:3', description: 'Presentation / Classic' },
  { id: '3:4', name: 'Card (3:4)', ratio: '3:4', width: 1080, height: 1440, iconLabel: '3:4', description: 'Photo Card / Pinterest' },
  { id: '2:1', name: 'Banner (2:1)', ratio: '2:1', width: 1600, height: 800, iconLabel: '2:1', description: 'Twitter / LinkedIn Banner' },
];

export const BLANK_TEMPLATE: StudioTemplate = {
  id: 'blank-canvas',
  version: '1.0',
  name: 'Blank Canvas',
  category: 'custom',
  description: 'Clean empty canvas with no preset layers',
  aspectRatio: '1:1',
  dimensions: { width: 1080, height: 1080 },
  background: {
    type: 'color',
    color: '#ffffff',
    gradient: { type: 'linear', colors: ['#ffffff', '#f8fafc'], angle: 180 },
    image: {
      url: null,
      fit: 'cover',
      offsetX: 0,
      offsetY: 0,
      zoom: 1,
      rotation: 0,
      flipH: false,
      flipV: false,
      filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, sepia: 0, invert: 0, hueRotate: 0, vignette: 0 },
    },
  },
  textLayers: [],
  stickers: [],
  frame: { enabled: false, color: '#ffffff', width: 0, inset: 0, radius: 0, style: 'solid' },
  watermark: { enabled: false, text: '', fontSize: 20, fontFamily: 'Inter', color: '#94a3b8', opacity: 0.5, position: 'bottom-right' },
  createdAt: Date.now(),
  updatedAt: Date.now(),
};

export const DEFAULT_TEMPLATES: StudioTemplate[] = [
  {
    id: 'classic-meme-01',
    version: '1.0',
    name: 'Classic Bold Meme',
    category: 'meme',
    description: 'Simple top & bottom bold caption meme',
    aspectRatio: '1:1',
    dimensions: { width: 1080, height: 1080 },
    background: {
      type: 'color',
      color: '#1e293b',
      gradient: { type: 'linear', colors: ['#1e293b', '#0f172a'], angle: 135 },
      image: {
        url: null,
        fit: 'cover',
        offsetX: 0,
        offsetY: 0,
        zoom: 1,
        rotation: 0,
        flipH: false,
        flipV: false,
        filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, sepia: 0, invert: 0, hueRotate: 0, vignette: 0 },
      },
    },
    textLayers: [
      {
        id: 'txt-top',
        name: 'Top Caption',
        text: 'WHEN THE CODE COMPILES',
        x: 540,
        y: 120,
        rotation: 0,
        fontFamily: 'Impact',
        fontSize: 72,
        fontWeight: '900',
        fontStyle: 'normal',
        color: '#FFFFFF',
        opacity: 1,
        align: 'center',
        verticalAlign: 'top',
        lineHeight: 1.15,
        letterSpacing: 2,
        transform: 'uppercase',
        strokeWidth: 8,
        strokeColor: '#000000',
        shadow: { enabled: true, color: 'rgba(0,0,0,0.8)', blur: 8, offsetX: 0, offsetY: 4 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 980,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 1,
      },
      {
        id: 'txt-bottom',
        name: 'Bottom Caption',
        text: 'ON THE FIRST TRY 🚀',
        x: 540,
        y: 960,
        rotation: 0,
        fontFamily: 'Impact',
        fontSize: 72,
        fontWeight: '900',
        fontStyle: 'normal',
        color: '#FFFFFF',
        opacity: 1,
        align: 'center',
        verticalAlign: 'bottom',
        lineHeight: 1.15,
        letterSpacing: 2,
        transform: 'uppercase',
        strokeWidth: 8,
        strokeColor: '#000000',
        shadow: { enabled: true, color: 'rgba(0,0,0,0.8)', blur: 8, offsetX: 0, offsetY: 4 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 980,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 2,
      },
    ],
    stickers: [],
    frame: { enabled: false, color: '#ffffff', width: 10, inset: 20, radius: 0, style: 'solid' },
    watermark: { enabled: false, text: '', fontSize: 22, fontFamily: 'Inter', color: 'rgba(255,255,255,0.4)', opacity: 0.5, position: 'bottom-right' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-news-02',
    version: '1.0',
    name: 'Card News (카드뉴스)',
    category: 'news',
    description: 'Clean headline and summary for social media news cards',
    aspectRatio: '1:1',
    dimensions: { width: 1080, height: 1080 },
    background: {
      type: 'color',
      color: '#f8fafc',
      gradient: { type: 'linear', colors: ['#ffffff', '#f1f5f9'], angle: 180 },
      image: {
        url: null,
        fit: 'cover',
        offsetX: 0,
        offsetY: 0,
        zoom: 1,
        rotation: 0,
        flipH: false,
        flipV: false,
        filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, sepia: 0, invert: 0, hueRotate: 0, vignette: 0 },
      },
    },
    textLayers: [
      {
        id: 'news-tag',
        name: 'News Tag',
        text: 'CARD NEWS',
        x: 540,
        y: 120,
        rotation: 0,
        fontFamily: 'Inter',
        fontSize: 22,
        fontWeight: '800',
        fontStyle: 'normal',
        color: '#059669',
        opacity: 1,
        align: 'left',
        verticalAlign: 'top',
        lineHeight: 1.2,
        letterSpacing: 2,
        transform: 'uppercase',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: true, color: '#ecfdf5', paddingX: 18, paddingY: 8, borderRadius: 8, borderWidth: 1, borderColor: '#a7f3d0' },
        maxWidth: 880,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 1,
      },
      {
        id: 'news-headline',
        name: 'Main Headline',
        text: '새로운 소식을 확인하세요',
        x: 540,
        y: 230,
        rotation: 0,
        fontFamily: 'Pretendard',
        fontSize: 64,
        fontWeight: '800',
        fontStyle: 'normal',
        color: '#0f172a',
        opacity: 1,
        align: 'left',
        verticalAlign: 'top',
        lineHeight: 1.3,
        letterSpacing: -1,
        transform: 'none',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 880,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 2,
      },
      {
        id: 'news-desc',
        name: 'Description',
        text: '간편하고 직관적인 카드뉴스 템플릿입니다.\n원하는 텍스트와 배경을 손쉽게 변경해보세요.',
        x: 540,
        y: 370,
        rotation: 0,
        fontFamily: 'Pretendard',
        fontSize: 32,
        fontWeight: '400',
        fontStyle: 'normal',
        color: '#475569',
        opacity: 1,
        align: 'left',
        verticalAlign: 'top',
        lineHeight: 1.6,
        letterSpacing: 0,
        transform: 'none',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 880,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 3,
      },
    ],
    stickers: [],
    frame: { enabled: true, color: '#e2e8f0', width: 2, inset: 40, radius: 24, style: 'solid' },
    watermark: { enabled: false, text: '', fontSize: 20, fontFamily: 'Inter', color: '#94a3b8', opacity: 0.5, position: 'bottom-right' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'minimal-quote-03',
    version: '1.0',
    name: 'Minimal Quote',
    category: 'quote',
    description: 'Clean quote and author citation with generous whitespace',
    aspectRatio: '4:5',
    dimensions: { width: 1080, height: 1350 },
    background: {
      type: 'color',
      color: '#ffffff',
      gradient: { type: 'linear', colors: ['#ffffff', '#f8fafc'], angle: 180 },
      image: {
        url: null,
        fit: 'cover',
        offsetX: 0,
        offsetY: 0,
        zoom: 1,
        rotation: 0,
        flipH: false,
        flipV: false,
        filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, sepia: 0, invert: 0, hueRotate: 0, vignette: 0 },
      },
    },
    textLayers: [
      {
        id: 'quote-body',
        name: 'Quote Text',
        text: '“Simplicity is the soul of efficiency.”',
        x: 540,
        y: 620,
        rotation: 0,
        fontFamily: 'Pretendard',
        fontSize: 58,
        fontWeight: '700',
        fontStyle: 'normal',
        color: '#0f172a',
        opacity: 1,
        align: 'center',
        verticalAlign: 'middle',
        lineHeight: 1.4,
        letterSpacing: -1,
        transform: 'none',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 820,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 1,
      },
      {
        id: 'quote-author',
        name: 'Author',
        text: '— AUSTIN FREEMAN',
        x: 540,
        y: 750,
        rotation: 0,
        fontFamily: 'Inter',
        fontSize: 22,
        fontWeight: '600',
        fontStyle: 'normal',
        color: '#64748b',
        opacity: 0.9,
        align: 'center',
        verticalAlign: 'middle',
        lineHeight: 1.2,
        letterSpacing: 4,
        transform: 'uppercase',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 700,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 2,
      },
    ],
    stickers: [],
    frame: { enabled: true, color: '#e2e8f0', width: 2, inset: 40, radius: 20, style: 'solid' },
    watermark: { enabled: false, text: '', fontSize: 20, fontFamily: 'Inter', color: '#71717a', opacity: 0.4, position: 'bottom-right' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'simple-banner-04',
    version: '1.0',
    name: 'Clean Banner (16:9)',
    category: 'social',
    description: 'Minimal landscape banner with center headline',
    aspectRatio: '16:9',
    dimensions: { width: 1920, height: 1080 },
    background: {
      type: 'gradient',
      color: '#0f172a',
      gradient: { type: 'linear', colors: ['#064e3b', '#0f172a'], angle: 135 },
      image: {
        url: null,
        fit: 'cover',
        offsetX: 0,
        offsetY: 0,
        zoom: 1,
        rotation: 0,
        flipH: false,
        flipV: false,
        filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, sepia: 0, invert: 0, hueRotate: 0, vignette: 0 },
      },
    },
    textLayers: [
      {
        id: 'banner-title',
        name: 'Main Title',
        text: 'Meme & Card Studio',
        x: 960,
        y: 480,
        rotation: 0,
        fontFamily: 'Montserrat',
        fontSize: 88,
        fontWeight: '900',
        fontStyle: 'normal',
        color: '#FFFFFF',
        opacity: 1,
        align: 'center',
        verticalAlign: 'middle',
        lineHeight: 1.2,
        letterSpacing: -1,
        transform: 'none',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: true, color: 'rgba(0,0,0,0.5)', blur: 16, offsetX: 0, offsetY: 6 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 1600,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 1,
      },
      {
        id: 'banner-sub',
        name: 'Subtitle',
        text: 'Create beautiful cards and graphics with ease',
        x: 960,
        y: 600,
        rotation: 0,
        fontFamily: 'Inter',
        fontSize: 34,
        fontWeight: '500',
        fontStyle: 'normal',
        color: '#a7f3d0',
        opacity: 0.9,
        align: 'center',
        verticalAlign: 'middle',
        lineHeight: 1.3,
        letterSpacing: 1,
        transform: 'none',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 1400,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 2,
      },
    ],
    stickers: [],
    frame: { enabled: false, color: '#fff', width: 0, inset: 0, radius: 0, style: 'solid' },
    watermark: { enabled: false, text: '', fontSize: 20, fontFamily: 'Inter', color: '#fff', opacity: 0.5, position: 'bottom-right' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'story-clean-05',
    version: '1.0',
    name: 'Story / Shorts (9:16)',
    category: 'social',
    description: 'Clean vertical format for Reels, Shorts, and Stories',
    aspectRatio: '9:16',
    dimensions: { width: 1080, height: 1920 },
    background: {
      type: 'gradient',
      color: '#0f172a',
      gradient: { type: 'linear', colors: ['#1e293b', '#0f172a'], angle: 180 },
      image: {
        url: null,
        fit: 'cover',
        offsetX: 0,
        offsetY: 0,
        zoom: 1,
        rotation: 0,
        flipH: false,
        flipV: false,
        filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, sepia: 0, invert: 0, hueRotate: 0, vignette: 0 },
      },
    },
    textLayers: [
      {
        id: 'story-header',
        name: 'Story Header',
        text: 'TODAY’S HIGHLIGHT',
        x: 540,
        y: 860,
        rotation: 0,
        fontFamily: 'Montserrat',
        fontSize: 64,
        fontWeight: '900',
        fontStyle: 'normal',
        color: '#FFFFFF',
        opacity: 1,
        align: 'center',
        verticalAlign: 'middle',
        lineHeight: 1.25,
        letterSpacing: 1,
        transform: 'uppercase',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: true, color: 'rgba(0,0,0,0.6)', blur: 16, offsetX: 0, offsetY: 4 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 900,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 1,
      },
      {
        id: 'story-sub',
        name: 'Story Subtitle',
        text: 'Clean & Simple Design',
        x: 540,
        y: 980,
        rotation: 0,
        fontFamily: 'Inter',
        fontSize: 34,
        fontWeight: '600',
        fontStyle: 'normal',
        color: '#10b981',
        opacity: 1,
        align: 'center',
        verticalAlign: 'middle',
        lineHeight: 1.2,
        letterSpacing: 2,
        transform: 'none',
        strokeWidth: 0,
        strokeColor: '#000',
        shadow: { enabled: false, color: '', blur: 0, offsetX: 0, offsetY: 0 },
        backgroundBox: { enabled: false, color: '', paddingX: 0, paddingY: 0, borderRadius: 0, borderWidth: 0, borderColor: '' },
        maxWidth: 800,
        autoScale: false,
        visible: true,
        locked: false,
        zIndex: 2,
      },
    ],
    stickers: [],
    frame: { enabled: false, color: '#fff', width: 0, inset: 0, radius: 0, style: 'solid' },
    watermark: { enabled: false, text: '', fontSize: 20, fontFamily: 'Inter', color: '#fff', opacity: 0.5, position: 'bottom-right' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
